version: "3"

networks:
  k6:
  #  grafana:
  pgrouting:

volumes:
  db-data:

services:
  pgrouting:
    build: ./pgrouting/
    image: camptocamp/osm2pgrouting:13-3.0-3.1.1-2.3.6
    networks:
      - pgrouting
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./osm:/osm
    environment:
      - POSTGRES_PASSWORD=postgres

  http2pgrouting:
    build: ./http2pgrouting/
    image: camptocamp/http2pgrouting
    networks:
      - pgrouting
      - k6
    ports:
      - "3000"

  valhalla:
    image: gisops/valhalla:3.0.9
    networks:
      - k6
    ports:
      - "8002"
    volumes:
      - ./valhalla/custom_files/:/custom_files
    environment:
      - min_x=-180
      - min_y=-90
      - max_x=180
      - max_y=90
      - use_tiles_ignore_pbf=False
      - force_rebuild=False
      - force_rebuild_elevation=False
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False

  #  influxdb:
  #    image: influxdb:latest
  #    networks:
  #      - k6
  #      - grafana
  #    ports:
  #      - "8086"
  #    environment:
  #      - INFLUXDB_DB=k6
  #
  #  grafana:
  #    image: grafana/grafana:latest
  #    networks:
  #      - grafana
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - ./grafana:/etc/grafana/provisioning/
  #    environment:
  #      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #      - GF_AUTH_ANONYMOUS_ENABLED=true
  #      - GF_AUTH_BASIC_ENABLED=false

  k6:
    image: loadimpact/k6:0.29.0
    networks:
      - k6
    volumes:
      - ./k6/scripts:/scripts
#    environment:
#      - K6_OUT=influxdb=http://influxdb:8086/k6
